"""empty message

Revision ID: 3133f7e61174
Revises: 
Create Date: 2019-08-29 19:43:49.721647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3133f7e61174'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Revoked_token',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=1000), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('bitcoinWalletId', sa.String(length=34), nullable=True),
    sa.Column('bitcoin_wallet_balance', sa.Integer(), nullable=False),
    sa.Column('ethereumWalletId', sa.String(length=42), nullable=True),
    sa.Column('ethereum_wallet_balance', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=False),
    sa.CheckConstraint('bitcoin_wallet_balance <= 1000000000'),
    sa.CheckConstraint('ethereum_wallet_balance <= 1000000000'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transaction',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('currency_amount', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('source_user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('target_user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('Revoked_token')
    # ### end Alembic commands ###
