"""empty message

Revision ID: 66c09113d49f
Revises: 3133f7e61174
Create Date: 2019-09-03 11:38:14.089488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c09113d49f'
down_revision = '3133f7e61174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'currency_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'currency_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
