"""empty message

Revision ID: da6bd786509e
Revises: 66c09113d49f
Create Date: 2019-09-03 12:27:43.848184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6bd786509e'
down_revision = '66c09113d49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'currency_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'currency_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
